# Generated by Django 5.2.15 on 2026-07-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='business_name',
            field=models.CharField(default='نظام التقسيط', max_length=255),
        ),
    ]
