# Generated by Django 5.2.15 on 2026-07-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_settings_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('completed', 'مكتمل'), ('overdue', 'متأخر'), ('cancelled', 'ملغي')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='installment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'نقدي'), ('wallet', 'محفظة'), ('instapay', 'إنستاباي')], max_length=20),
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق'), ('paid', 'مدفوع'), ('late', 'متأخر'), ('partial', 'جزئي')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reminder', 'تذكير'), ('overdue', 'متأخر'), ('info', 'معلومة')], max_length=20),
        ),
    ]
