# Generated by Django 5.2.15 on 2026-07-04 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contract_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier'),
        ),
    ]
