# Generated by Django 5.2.15 on 2026-07-06 21:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contract_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at'], 'verbose_name': 'عقد', 'verbose_name_plural': 'العقود'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'عميل', 'verbose_name_plural': 'العملاء'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date'], 'verbose_name': 'مصروف', 'verbose_name_plural': 'المصروفات'},
        ),
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['installment_number'], 'verbose_name': 'قسط', 'verbose_name_plural': 'الأقساط'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'تنبيه', 'verbose_name_plural': 'التنبيهات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'فئة منتج', 'verbose_name_plural': 'فئات المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'إعدادات', 'verbose_name_plural': 'الإعدادات'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-created_at'], 'verbose_name': 'تاجر', 'verbose_name_plural': 'التجار'},
        ),
        migrations.AlterModelOptions(
            name='suppliercategory',
            options={'verbose_name': 'فئة تاجر', 'verbose_name_plural': 'فئات التجار'},
        ),
        migrations.AlterModelOptions(
            name='supplierpurchase',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'مشتريات', 'verbose_name_plural': 'المشتريات'},
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AddField(
            model_name='supplierpurchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='التكلفة الفعلية'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='calculation_mode',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, verbose_name='نوع الحساب'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم العقد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر العميل'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مقدم'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة القسط'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='نسبة الفائدة'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='months_count',
            field=models.IntegerField(verbose_name='عدد الأشهر'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_due_day',
            field=models.IntegerField(default=1, verbose_name='يوم الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المتبقي'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ البداية'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('completed', 'مكتمل'), ('overdue', 'متأخر'), ('cancelled', 'ملغي')], default='active', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier', verbose_name='التاجر'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='إجمالي المبلغ'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='إجمالي الفائدة'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, verbose_name='واتساب'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, max_length=255, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(verbose_name='تاريخ المصروف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='core.contract', verbose_name='العقد'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='due_date',
            field=models.DateField(verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='installment_number',
            field=models.IntegerField(verbose_name='رقم القسط'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'نقدي'), ('wallet', 'محفظة'), ('instapay', 'إنستاباي')], max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق'), ('paid', 'مدفوع'), ('late', 'متأخر'), ('partial', 'جزئي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contract', verbose_name='العقد'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.installment', verbose_name='القسط'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='مقروء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reminder', 'تذكير'), ('overdue', 'متأخر'), ('info', 'معلومة')], max_length=20, verbose_name='نوع التنبيه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=255, verbose_name='الماركة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='product',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر التقديري'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='صورة المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='business_name',
            field=models.CharField(default='نظام التقسيط', max_length=255, verbose_name='اسم النشاط'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.5'), max_digits=7, verbose_name='النسبة الشهرية الافتراضية %'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_payment_due_day',
            field=models.IntegerField(default=1, verbose_name='يوم الاستحقاق الافتراضي'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل واتساب'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.suppliercategory', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='suppliercategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='supplierpurchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='supplierpurchase',
            name='image',
            field=models.ImageField(blank=True, upload_to='supplier_purchases/', verbose_name='صورة الفاتورة'),
        ),
        migrations.AlterField(
            model_name='supplierpurchase',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='supplierpurchase',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='supplierpurchase',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='supplierpurchase',
            name='purchase_date',
            field=models.DateField(verbose_name='تاريخ الشراء'),
        ),
        migrations.AlterField(
            model_name='supplierpurchase',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الشراء'),
        ),
        migrations.AlterField(
            model_name='supplierpurchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier', verbose_name='التاجر'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='core_contra_status_2b38a6_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date'], name='core_contra_start_d_664ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='core_custom_name_b5e864_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['status'], name='core_instal_status_9f0fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['due_date'], name='core_instal_due_dat_05635e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='core_produc_name_be3252_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='core_suppli_name_c90f73_idx'),
        ),
    ]
