# Generated by Django 5.2.15 on 2026-07-06 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contract_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierpurchase',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'عملية شراء منتج', 'verbose_name_plural': 'سجل شراء المنتجات'},
        ),
        migrations.AddField(
            model_name='supplierpurchase',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_records', to='core.contract', verbose_name='العقد'),
        ),
        migrations.AddField(
            model_name='supplierpurchase',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_purchases', to='core.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='supplierpurchase',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_records', to='core.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='supplierpurchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier', verbose_name='التاجر'),
        ),
    ]
