# Generated by Django 5.2.15 on 2026-07-07 13:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_supplierpurchase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100000.00'))], verbose_name='التكلفة الفعلية'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100000.00'))], verbose_name='سعر العميل'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100000.00'))], verbose_name='مقدم'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100000.00'))], verbose_name='قيمة القسط'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_due_day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='يوم الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100000.00'))], verbose_name='المبلغ المتبقي'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100000.00'))], verbose_name='إجمالي المبلغ'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100000.00'))], verbose_name='إجمالي الفائدة'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100000.00'))], verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100000.00'))], verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100000.00'))], verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='product',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100000.00'))], verbose_name='السعر التقديري'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_payment_due_day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='يوم الاستحقاق الافتراضي'),
        ),
        migrations.AlterField(
            model_name='supplierpurchase',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100000.00'))], verbose_name='سعر الشراء'),
        ),
    ]
