# Generated by Django 5.2.15 on 2026-07-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_contract_actual_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=150, verbose_name='المستخدم')),
                ('action', models.CharField(choices=[('create', 'إضافة'), ('update', 'تعديل'), ('delete', 'حذف'), ('payment', 'دفع'), ('reset', 'إلغاء دفع'), ('mark_completed', 'تعليم مكتمل'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الحركة')),
                ('model_name', models.CharField(max_length=50, verbose_name='النموذج')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='وصف الكائن')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('previous_value', models.JSONField(blank=True, null=True, verbose_name='القيمة السابقة')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='القيمة الجديدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحركة')),
            ],
            options={
                'verbose_name': 'سجل حركة',
                'verbose_name_plural': 'سجل الحركات',
                'ordering': ['-created_at'],
            },
        ),
    ]
