# Generated by Django 5.2.15 on 2026-07-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='received_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='المستلم (كاش)'),
        ),
        migrations.AddField(
            model_name='installment',
            name='transfer_image',
            field=models.ImageField(blank=True, upload_to='transfers/', verbose_name='صورة التحويل'),
        ),
        migrations.AddField(
            model_name='installment',
            name='transfer_sender_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم المحفظة/الحساب المرسل منه'),
        ),
        migrations.AddField(
            model_name='installment',
            name='transfer_sender_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم المرسل'),
        ),
    ]
