# Generated by Django 5.2.15 on 2026-07-08 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_account_activitylog_account_contract_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='الموديل'),
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='النوع')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.account', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'نوع منتج',
                'verbose_name_plural': 'أنواع المنتجات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producttype', verbose_name='النوع'),
        ),
    ]
