# Generated by Django 5.2.15 on 2026-07-08 07:22

from django.db import migrations


DEFAULT_TYPES = [
    "غسالة",
    "تلاجة",
    "تلفزيون",
    "مكيف",
    "سخان",
    "بوتاجاز",
    "شاشة",
    "خلاط",
    "مروحة",
    "ديب فريزر",
    "غسالة أطباق",
    "ميكروويف",
    "فرن",
    "مجفف",
    "مكنسة",
]


def add_default_types(apps, schema_editor):
    ProductType = apps.get_model("core", "ProductType")
    Account = apps.get_model("core", "Account")

    for account in Account.objects.all():
        for name in DEFAULT_TYPES:
            ProductType.objects.get_or_create(account=account, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_product_model_name_producttype_product_product_type"),
    ]

    operations = [
        migrations.RunPython(add_default_types, migrations.RunPython.noop),
    ]
