# Generated by Django 5.2.15 on 2026-07-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_default_product_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية العقد'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق'), ('paid', 'مدفوع'), ('late', 'متأخر'), ('partial', 'جزئي'), ('overpaid', 'زيادة')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
