# Generated by Django 5.2.15 on 2026-07-08 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contract_end_date_and_overpaid_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='core.account', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'مستلم',
                'verbose_name_plural': 'المستلمون',
                'ordering': ['name'],
                'unique_together': {('account', 'name')},
            },
        ),
        migrations.AddField(
            model_name='installment',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments', to='core.receiver', verbose_name='المستلم'),
        ),
    ]
