# Generated by Django 5.2.15 on 2026-07-26 09:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_receiver_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('month', models.IntegerField(verbose_name='الشهر')),
                ('expected_monthly_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100000.00'))], verbose_name='الدخل المتوقع الشهري')),
                ('collected_amount_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100000.00'))], verbose_name='تعديل المحصل يدويًا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.account', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'الدخل الشهري',
                'verbose_name_plural': 'الدخل الشهري',
                'ordering': ['-year', '-month'],
                'unique_together': {('account', 'year', 'month')},
            },
        ),
    ]
