# Generated by Django 5.2.15 on 2026-09-14 03:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_monthlyincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('completed', 'مكتمل'), ('overdue', 'متأخر'), ('cancelled', 'ملغي'), ('early_completed', 'مكتمل (إغلاق مبكر)')], default='active', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق'), ('paid', 'مدفوع'), ('late', 'متأخر'), ('partial', 'جزئي'), ('overpaid', 'زيادة'), ('closed', 'معفي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100000.00'))], verbose_name='المبلغ')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'نقدي'), ('wallet', 'محفظة'), ('instapay', 'إنستاباي')], max_length=20, verbose_name='طريقة الدفع')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('received_by', models.CharField(blank=True, max_length=255, verbose_name='المستلم (كاش)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.account', verbose_name='الحساب')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.installment', verbose_name='القسط')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.receiver', verbose_name='المستلم')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['paid_date', 'created_at'],
                'indexes': [models.Index(fields=['payment_method'], name='core_paymen_payment_91235d_idx'), models.Index(fields=['paid_date'], name='core_paymen_paid_da_522c76_idx')],
            },
        ),
    ]
